export const skillFiEscrowAbi = [
  {
    type: "function",
    name: "createMatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "entryFee", type: "uint256" },
      { name: "expectedPlayer1", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "joinMatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "startMatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveMatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "winner", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "disputeMatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelMatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "reclaimReadyMatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "reclaimActiveMatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "winner", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "matches",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [
      { name: "player1", type: "address" },
      { name: "player2", type: "address" },
      { name: "entryFee", type: "uint256" },
      { name: "createdAt", type: "uint256" },
      { name: "player1Deposited", type: "bool" },
      { name: "player2Deposited", type: "bool" },
      { name: "status", type: "uint8" },
      { name: "startedAt", type: "uint256" },
      { name: "winner", type: "address" },
      { name: "feeBpsAtCreation", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "platformFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "readyMatchGrace",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "OPERATOR_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "hasRole",
    stateMutability: "view",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "event",
    name: "MatchCreated",
    inputs: [
      { name: "matchId", type: "uint256", indexed: true },
      { name: "entryFee", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerJoined",
    inputs: [
      { name: "matchId", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchReady",
    inputs: [{ name: "matchId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchStarted",
    inputs: [{ name: "matchId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchResolved",
    inputs: [
      { name: "matchId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "prize", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchCancelled",
    inputs: [{ name: "matchId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchDisputed",
    inputs: [{ name: "matchId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchRefunded",
    inputs: [
      { name: "matchId", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MatchExpired",
    inputs: [{ name: "matchId", type: "uint256", indexed: true }],
    anonymous: false,
  },
] as const;
