import type { Metadata } from "next";
import { InfoPageShell, InfoSection } from "@/components/InfoPageShell";

export const metadata: Metadata = { title: "About SkillFi Arena", description: "The mission, product thesis, and roadmap behind SkillFi Arena." };

export default function AboutPage() {
  return <InfoPageShell eyebrow="About" title="A settlement layer for digital skill" intro="SkillFi Arena is building a transparent way for players to create, fund, complete, and settle peer-to-peer skill competitions in USDC.">
    <InfoSection title="Why we are building it"><p>Competitive communities are global, but their payment options are fragmented, slow, and often opaque. SkillFi pairs familiar challenge-based play with explicit onchain rules so participants can understand where funds are and how a match resolves.</p></InfoSection>
    <InfoSection title="What exists today"><p>The current MVP includes wallet-based identity, two-player invitations, atomic match acceptance, USDC escrow contracts, lifecycle reconciliation, risk-limit foundations, and user-visible audit records. The escrow lifecycle has been exercised end to end on Base Sepolia and Arc Testnet. The Arc run used Circle&apos;s canonical USDC interface and verified two player deposits, match start, result settlement, winner payout, and zero residual escrow balance.</p></InfoSection>
    <InfoSection title="What comes next"><p>The next technical milestone is a controlled Arc pilot covering real user onboarding, repeated matches, cancellation and refund operations, and measurable reliability. The pilot will track funded wallets, completed settlements, repeat participation, failure rates, and settlement time before any broader release.</p></InfoSection>
    <InfoSection title="Founder"><p><strong className="font-semibold text-white">Zeynep Balkan</strong> is a business development and strategic partnerships professional with more than seven years of experience across mobile gaming, technology, Web3, and digital ecosystems. Her work spans international partner acquisition, go-to-market strategy, commercial negotiations, and strategic account development.</p><p>She has evaluated and engaged with more than 50 gaming, Web3, AI, and technology companies, advised over 20 projects, and worked with founders, studios, developers, investors, and technology partners across international markets. Her background also includes co-founding an early-stage gaming venture and serving as a Women in Games Ambassador.</p><p><a className="font-medium text-arena-accent hover:text-cyan-300" href="https://www.linkedin.com/in/zeynep-balkan-3709a8193" target="_blank" rel="noreferrer">View verified professional profile →</a></p></InfoSection>
    <InfoSection title="Project status"><p>SkillFi Arena is currently a founder-led, pre-incorporation project based in Türkiye. The site does not imply a registered company, partnerships, funding, or credentials that have not been confirmed.</p></InfoSection>
  </InfoPageShell>;
}
