"use client";

import Link from "next/link";
import { WalletConnect } from "@/components/WalletConnect";
import { MarketingDetails, MarketingHero, PilotSection } from "@/components/MarketingSections";

export function LandingPage() {
  return <div className="min-h-screen"><header className="sticky top-0 z-40 border-b border-white/5 bg-arena-bg/85 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg border border-arena-accent/30 bg-arena-accent/10 font-display text-lg font-bold text-arena-accent shadow-arena-glow">S</span><div><p className="font-display text-lg font-bold leading-none tracking-[0.12em] text-white">SKILLFI</p><p className="mt-1 text-[10px] uppercase tracking-[0.28em] text-arena-muted">Arena</p></div></Link><nav className="hidden items-center gap-7 text-sm text-arena-muted md:flex"><a href="#how-it-works" className="hover:text-white">How it works</a><a href="#technology" className="hover:text-white">Technology</a><Link href="/games" className="hover:text-white">Games</Link><Link href="/guilds" className="hover:text-white">Guilds</Link></nav><div className="flex items-center gap-3"><Link href="/dashboard" className="hidden rounded-lg border border-white/10 px-3 py-2 text-xs font-bold text-white hover:border-cyan-300/40 sm:block">OPEN APP</Link><WalletConnect /></div></div></header><MarketingHero /><MarketingDetails /><section className="border-t border-white/5 bg-white/[0.015]"><div className="mx-auto grid max-w-6xl gap-5 px-5 py-20 sm:px-8 md:grid-cols-3">{[["Game Library","Discover competitive titles in a Steam-like library built around verified play.","/games"],["Challenge Arena","Create, fund and accept head-to-head challenges in a dedicated live lobby.","/challenges"],["Guild Wars","Coordinate a player-owned guild, vote on strategy and fight for season rank.","/guilds"]].map(([title,copy,href])=><Link key={title} href={href} className="group rounded-2xl border border-white/10 bg-arena-surface p-6 transition hover:-translate-y-1 hover:border-cyan-300/30"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">ENTER</p><h2 className="mt-6 font-display text-2xl font-bold text-white">{title}</h2><p className="mt-3 leading-7 text-arena-muted">{copy}</p><span className="mt-7 inline-block text-sm font-bold text-white group-hover:text-cyan-300">EXPLORE →</span></Link>)}</div></section><PilotSection /><footer className="border-t border-white/5"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-5 py-8 text-xs text-arena-muted sm:flex-row sm:items-center sm:justify-between sm:px-8"><p>© {new Date().getFullYear()} SkillFi Arena. Built for verifiable competition.</p><div className="flex gap-5"><Link href="/about">About</Link><Link href="/security">Security</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></footer></div>;
}
