import type { Metadata } from "next";
import Link from "next/link";
import { InfoPageShell, InfoSection } from "@/components/InfoPageShell";

export const metadata: Metadata = { title: "Controlled Pilot Runbook", description: "Operational checklist and stop conditions for SkillFi Arena controlled test sessions." };

export default function PilotRunbookPage() {
  return <InfoPageShell eyebrow="Controlled beta operations" title="Pilot session runbook" intro="Use this checklist for every scheduled test window. A session must not start until a named human operator accepts incident ownership and confirms the testnet-only boundary.">
    <InfoSection title="Assign before opening the session"><Checklist items={["Name one session lead and one backup incident owner.", "Record the test window, invited participants, and support channel.", "Confirm every participant is active in the cohort admin console and has completed adult, terms, and privacy consent.", "Confirm only testnet wallets and test assets are in use; never request seed phrases or identity documents."]}/></InfoSection>
    <InfoSection title="Go / no-go checks"><div className="grid gap-3 sm:grid-cols-2"><Gate title="GO" tone="green" items={["Health endpoint reports ready", "Five game records are present", "Hosted schema checks pass", "Support owner is reachable", "No unresolved critical incident"]}/><Gate title="NO-GO" tone="amber" items={["Any production asset is detected", "Authentication or consent cannot be verified", "Match cancellation/refund path is unavailable", "Result integrity is uncertain", "Admin or service-role access is exposed"]}/></div></InfoSection>
    <InfoSection title="During the window"><Checklist items={["Admit only named cohort participants.", "Observe onboarding, game completion, cancellation, dispute, and result-save behavior without requesting sensitive data.", "Record timestamps, affected match IDs, and reproducible symptoms for failures.", "Do not describe test ratings, tokens, badges, or simulated results as money, prizes, returns, or traction."]}/></InfoSection>
    <InfoSection title="Stop and contain"><p>Pause new matches immediately for unauthorized access, suspected key exposure, incorrect settlement, loss of result integrity, repeated authentication failure, or accidental production-asset use. Preserve audit identifiers, disable the affected test window, notify participants through the agreed support channel, and do not resume until the session lead documents the decision.</p></InfoSection>
    <InfoSection title="Close the session"><Checklist items={["Confirm all started matches reached a documented terminal or recovery state.", "Export the minimum necessary cohort summary and store it securely.", "Review five-game completion, failure rate, feedback, and unresolved incidents.", "Mark participants complete only after their agreed checklist is finished.", "Schedule remediation and a fresh go/no-go review before the next window."]}/></InfoSection>
    <div className="flex flex-wrap gap-4"><Link href="/pilot/admin" className="rounded-lg bg-arena-accent px-5 py-3 text-sm font-bold text-arena-bg">OPEN COHORT ADMIN</Link><Link href="/api/health" className="rounded-lg border border-white/10 px-5 py-3 text-sm font-bold text-white">CHECK LIVE HEALTH</Link><Link href="/pilot" className="px-2 py-3 text-sm font-semibold text-arena-accent">← Pilot overview</Link></div>
  </InfoPageShell>;
}

function Checklist({ items }: { items: string[] }) { return <ul className="space-y-3">{items.map((item) => <li key={item} className="flex gap-3"><span aria-hidden="true" className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded border border-white/15 text-[10px] text-arena-accent">✓</span><span>{item}</span></li>)}</ul>; }

function Gate({ title, tone, items }: { title: string; tone: "green" | "amber"; items: string[] }) { const style = tone === "green" ? "border-emerald-300/20 bg-emerald-300/[.05] text-emerald-200" : "border-amber-300/20 bg-amber-300/[.05] text-amber-100"; return <div className={`rounded-xl border p-5 ${style}`}><p className="font-display text-xl font-bold">{title}</p><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
