import type { Metadata } from "next";
import { InfoPageShell, InfoSection } from "@/components/InfoPageShell";

export const metadata: Metadata = { title: "Technology", description: "SkillFi Arena product architecture and Arc integration roadmap." };

export default function TechnologyPage() {
  return <InfoPageShell eyebrow="Technology" title="From game state to money state" intro="SkillFi separates the social match experience from financial settlement, then reconciles both through explicit identifiers, lifecycle states, and immutable events.">
    <InfoSection title="Current product architecture"><div className="grid gap-3 sm:grid-cols-2"><Layer name="Product" detail="Next.js application for lobby, invitations, matches, and user history." /><Layer name="Identity" detail="Privy authentication with verified server-side identity resolution." /><Layer name="Application state" detail="Supabase/Postgres records for profiles, challenges, matches, participants, limits, and audit events." /><Layer name="Settlement" detail="Solidity USDC escrow with an automated Hardhat test suite and server reconciliation." /></div></InfoSection>
    <InfoSection title="Arc-native deployment"><p>The SkillFi escrow is deployed on Arc Testnet at <a className="break-all font-medium text-arena-accent hover:text-cyan-300" href="https://testnet.arcscan.app/address/0x263c8Eed47F11b7cd7E292139Afb5F774F033BFc" target="_blank" rel="noreferrer">0x263c8Eed47F11b7cd7E292139Afb5F774F033BFc</a>. Automated checks confirm bytecode, operator and arbiter roles, treasury, fee configuration, and the canonical USDC interface.</p><p>Public two-player runs completed payout, cancellation with two refunds, and participant dispute with arbiter resolution. Every completed path returned the escrow&apos;s canonical USDC balance to zero, and duplicate terminal actions were rejected. <a className="font-medium text-arena-accent hover:text-cyan-300" href="https://testnet.arcscan.app/tx/0x507ebe3f9c37bc5ea4deee77cbc6cf80a524c3471c2082937253717eb6fe7153" target="_blank" rel="noreferrer">View the arbitration transaction →</a></p><ol className="list-decimal space-y-3 pl-5"><li>Players hold or receive USDC through an eligible wallet path.</li><li>Both deposits enter a match-specific escrow lifecycle on Arc.</li><li>Application records reference the canonical contract match and transaction identifiers.</li><li>An authorized outcome advances settlement; cancellation follows an explicit refund path.</li><li>Indexing and reconciliation confirm the final state and expose a user-visible audit trail.</li></ol></InfoSection>
    <InfoSection title="Circle product path"><p>Arc and canonical USDC are active in the testnet deployment. Circle Wallets will be evaluated for lower-friction onboarding. CCTP or Gateway will be evaluated as a later liquidity path for users whose USDC begins on another supported network. The site distinguishes completed integrations from planned work.</p></InfoSection>
    <InfoSection title="Measured outcomes"><p>The pilot will track unique funded wallets, completed Arc settlements, USDC settlement volume, repeat-funded-user rate, median completion time, refund rate, transaction failures, and reconciliation exceptions. Artificially subsidized volume will not be counted as organic traction.</p></InfoSection>
  </InfoPageShell>;
}

function Layer({ name, detail }: { name: string; detail: string }) {
  return <div className="rounded-xl border border-white/10 bg-arena-surface p-4"><p className="font-semibold text-white">{name}</p><p className="mt-2 text-sm leading-6 text-arena-muted">{detail}</p></div>;
}
